### ISSUE TITLE
Sanitarise the data

### ISSUE THREAD

**Issue by David-2D3FE9** [br-automation-com/mappDatabase-Demo#3]
Hello, 

I think that it could be a good thing to sanitarise incoming data.  
For example data stored in the database can came from non fixed sources.  
e.g in my application some text can be provided from text input and TMX files.
So we can find in these string some problematic char like an apostrophe `'` witch will crash the SQL  request.

In my case I used the `REPLACE` function in the PLC to replace the `'` with a space but it should be more convenient to get it in the python.  
This problem increase the utility of #2

**Comment by stephan1827** [comment]
The ' character shows up as $' on the PLC but I would not change that since some customers might want the character to show up. I have tried ' and " in a string on the SQL server and the script does not crash. Can you provide a string that would cause issues.

**Comment by David-2D3FE9** [comment]
The string was comming from Tmx file.  
I read the .tmx with `ArTextSysGetText()` and store it to a string.  
Then the string is sended by mappDatabase.  
(This tmx is used for alarm description, and i also store alarms in sql)

The error message returned was a generic like (...there is an error in your query check your syntax..)  
In the traceback I was able to saw the query with the `'`

One of the sended string is:
`Boucle d'arrêt d'urgence`

![image](https://user-images.githubusercontent.com/64800039/142413733-70109669-7106-4244-9078-c32f4f3b07d8.png)

**Comment by stephan1827** [comment]
I can reproduce the issue and will try to fix it in the python script.

**Comment by stephan1827** [comment]
I tried to fix the issue with regex but there is no robust solution on the python script side. To fix the issue the right way the string 'Boucle d'arrêt d'urgence' must be converted in 'Boucle 'd''arrêt d''urgence'. The single quotes (') must be replaced with two single quotes (''). Trying to do this with regex causes conflicts with other single quotes within the same SQL string. I ended up with something like this

# fix quotes in strings
sql = re.sub(r"((?<!\ )(?<!\=)(?<!\()'(?!\))(?!\d)(?!')(?!,)(?! )).{1}", "''", sql)

Still, this is not stable and has several limitations where the single quote can be. For example, it cannot be at the beginning of a string because there is no good way to figure out if this single quote is within the string or the quote that surrounds the string. I also see issues when reading the text "d'arrêt d'urgence" back from the SQL database. The single quotes are fine but the "ê" is not converted back correct which leaves me with this string "d'rrÃªt d'rgence"

So for now I think the best and only reliable way is to convert the string on the PLC side.

**Comment by David-2D3FE9** [comment]
Ok,
Iindeed this is not trivial, 
Wathever, thanks for your support and fast responses :-)

**Comment by stephan1827** [comment]
You are welcome, let me know if you find any other issue or have recommendations for improvement
